
# Generated by Django 5.2.6 on 2025-09-23 08:33


import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('prof', 'Prof.'), ('dr', 'Dr.'), ('eng', 'Eng.'), ('mr', 'Mr.'), ('mrs', 'Mrs.'), ('ms', 'Ms')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('organization_type', models.CharField(choices=[('govt', 'Government Agency'), ('private', 'Private Company'), ('academia', 'Academic Institution'), ('association', 'Sector Association'), ('advocacy', 'Industry Advocacy Groups'), ('dev_partner', 'Development Partners'), ('other', 'Others')], max_length=20)),
                ('other_organization_type', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('other_interest', models.CharField(blank=True, max_length=255, null=True)),
                ('accessibility_needs', models.TextField(blank=True, null=True)),
                ('updates_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
    ]
