# Generated by Django 5.2.6 on 2025-09-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='organization_type',
            field=models.CharField(choices=[('Government Agency', 'Government Agency'), ('Private Company', 'Private Company'), ('Academic Institution', 'Academic Institution'), ('Sector Association', 'Sector Association'), ('Industry Advocacy Groups', 'Industry Advocacy Groups'), ('Development Partners', 'Development Partners'), ('other', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='title',
            field=models.CharField(blank=True, choices=[('Prof', 'Prof.'), ('Dr', 'Dr.'), ('Eng', 'Eng.'), ('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms')], max_length=10),
        ),
    ]
