# Generated by Django 5.2.5 on 2025-09-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('govt', 'Government'), ('private', 'Private Sector'), ('startup', 'Startup'), ('academia', 'Academia'), ('student', 'Student'), ('investor', 'Investor'), ('other', 'Other')], max_length=20)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('accessibility_needs', models.TextField(blank=True, null=True)),
                ('updates_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
