# Generated by Django 5.2.7 on 2025-10-07 08:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SummitGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='SummitPartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Official name of the partner or sponsor', max_length=150)),
                ('logo', models.ImageField(help_text="Upload the partner's logo image", upload_to='partners/logos/')),
                ('website', models.URLField(blank=True, help_text='Optional: Link to partner website', null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of display on the sponsors section')),
                ('is_active', models.BooleanField(default=True, help_text='Show or hide this partner on the site')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SummitScheduleDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. Day 1 - November 10', max_length=100)),
                ('date', models.DateField(help_text='Date of the event day.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Schedule Day',
                'verbose_name_plural': 'Schedule Days',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SummitSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_type', models.CharField(choices=[('keynote', 'Keynote'), ('networking', 'Networking'), ('panel', 'Panel Discussion'), ('break', 'Break'), ('workshop', 'Workshop'), ('hackathon', 'Hackathon'), ('exhibition', 'Exhibition'), ('closing', 'Closing'), ('other', 'Other')], default='other', max_length=50)),
                ('title', models.CharField(help_text="e.g. 'Software Ecosystem Landscape'", max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=100, null=True)),
                ('is_break', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order of appearance in the slot')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['timeslot__start_time', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SummitSpeaker',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=150)),
                ('position', models.CharField(max_length=150)),
                ('organization', models.CharField(max_length=250)),
                ('track', models.CharField(blank=True, help_text='E.g., Keynote Speaker, Panelist, Moderator', max_length=100)),
                ('topic', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='speakers/')),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('twitter_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='SummitPanelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text="e.g. 'Keynote Address', 'Presentation', 'Moderator'", max_length=150)),
                ('name', models.CharField(blank=True, help_text="e.g. 'Dr. Jane Doe'", max_length=200, null=True)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panelists', to='summitPage.summitsession')),
            ],
            options={
                'verbose_name': 'Panelist',
                'verbose_name_plural': 'Panelists',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SummitTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('label', models.CharField(blank=True, help_text="Optional label like 'All Day' or 'Morning'", max_length=100)),
                ('duration', models.CharField(blank=True, help_text='e.g. 1 hr 30 min', max_length=50, null=True)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeslots', to='summitPage.summitscheduleday')),
            ],
            options={
                'verbose_name': 'Time Slot',
                'verbose_name_plural': 'Time Slots',
                'ordering': ['start_time'],
            },
        ),
        migrations.AddField(
            model_name='summitsession',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='summitPage.summittimeslot'),
        ),
    ]
