# Generated by Django 5.2.7 on 2025-10-20 16:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExhibitionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SummitSponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, help_text='Business registration number or PIN (optional)', max_length=100, null=True)),
                ('sector', models.CharField(help_text='Industry or sector of operation', max_length=150)),
                ('website', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, help_text='Optional logo upload', null=True, upload_to='uploads/sponsors/logos/')),
                ('contact_full_name', models.CharField(max_length=150)),
                ('contact_designation', models.CharField(max_length=150)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=50)),
                ('areas_of_interest', models.JSONField(default=list, help_text='List of selected areas of interest (checkboxes)')),
                ('proposed_contribution', models.TextField(blank=True, help_text='Description of proposed contribution')),
                ('proposal_file', models.FileField(blank=True, help_text='Optional detailed proposal file', null=True, upload_to='uploads/sponsors/proposals/')),
                ('company_profile', models.FileField(blank=True, help_text='Upload company profile (PDF/DOCX)', null=True, upload_to='uploads/sponsors/documents/')),
                ('tax_compliance_certificate', models.FileField(blank=True, help_text='Tax compliance certificate or letter of intent', null=True, upload_to='uploads/sponsors/documents/')),
                ('consent_confirmation', models.BooleanField(default=False, help_text='Confirms accuracy and agreement with Government of Kenya partnership guidelines')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Summit Sponsor',
                'verbose_name_plural': 'Summit Sponsors',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='exhibit_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='summitPage.exhibitioncategory', verbose_name='Exhibition Category'),
        ),
    ]
