# Generated by Django 5.2.5 on 2025-09-09 10:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0002_registrant_delete_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='unsubscribe_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
