# Generated by Django 5.2.7 on 2025-10-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0002_summitgallery_summitpartner_summitscheduleday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='national_id_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='National ID Number'),
        ),
        migrations.AddField(
            model_name='registrant',
            name='national_id_scan',
            field=models.FileField(blank=True, null=True, upload_to='uploads/id_scans/', verbose_name='Scanned National ID (JPG/PDF)'),
        ),
        migrations.AddField(
            model_name='registrant',
            name='passport_photo',
            field=models.FileField(blank=True, null=True, upload_to='uploads/passport_photos/', verbose_name='Passport Photo (JPG/PDF)'),
        ),
    ]
