# Generated by Django 5.2.6 on 2025-10-02 08:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0002_alter_registrant_organization_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, choices=[('', 'Select Title'), ('Prof', 'Prof.'), ('Dr', 'Dr.'), ('Eng', 'Eng.'), ('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms')], max_length=10)),
                ('first_name', models.CharField(max_length=100)),
                ('second_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('organization_type', models.CharField(choices=[('', 'Select Organization'), ('Government Agency', 'Government Agency'), ('Private Company', 'Private Company'), ('Academic Institution', 'Academic Institution'), ('Sector Association', 'Sector Association'), ('Industry Advocacy Groups', 'Industry Advocacy Groups'), ('Development Partners', 'Development Partners'), ('Student', 'Student'), ('other', 'Others')], max_length=100)),
                ('other_organization_type', models.CharField(blank=True, max_length=255, null=True)),
                ('job_title', models.CharField(blank=True, max_length=255)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('other_interest', models.CharField(blank=True, max_length=255, null=True)),
                ('accessibility_needs', models.TextField(blank=True, null=True)),
                ('updates_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribe_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='registrant',
            name='organization_type',
            field=models.CharField(choices=[('', 'Select Organization'), ('Government Agency', 'Government Agency'), ('Private Company', 'Private Company'), ('Academic Institution', 'Academic Institution'), ('Sector Association', 'Sector Association'), ('Industry Advocacy Groups', 'Industry Advocacy Groups'), ('Development Partners', 'Development Partners'), ('Student', 'Student'), ('other', 'Others')], max_length=100),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='title',
            field=models.CharField(blank=True, choices=[('', 'Select Title'), ('Prof', 'Prof.'), ('Dr', 'Dr.'), ('Eng', 'Eng.'), ('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms')], max_length=10),
        ),
    ]
