# Generated by Django 5.2.7 on 2025-10-11 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0003_registrant_national_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='category',
            field=models.CharField(choices=[('', 'Select Category'), ('exhibitor', 'Exhibitor'), ('delegate', 'Delegate'), ('speaker', 'Speaker'), ('student', 'Student')], default='UNKNOWN', max_length=50, verbose_name='Registration Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrant',
            name='privacy_agreed',
            field=models.BooleanField(default=False, verbose_name='Agreed to Privacy Policy'),
        ),
    ]
