# Generated by Django 5.2.5 on 2025-09-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0003_registrant_unsubscribe_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrant',
            name='other_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='registrant',
            name='other_interest',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
