# Generated by Django 5.2.7 on 2025-10-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0003_apiaccesslog'),
        ('summitPage', '0004_registrant_category_registrant_privacy_agreed'),
    ]

    operations = [
    ]
