# Generated by Django 5.2.7 on 2025-10-11 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0005_merge_20251011_1213'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('registrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emaillog', to='summitPage.registrant')),
            ],
        ),
    ]
