# Generated by Django 5.2.7 on 2025-10-13 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0006_emaillog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='other_interest',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
