# Generated by Django 5.2.7 on 2025-10-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0007_alter_registrant_other_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='other_interest',
            field=models.TextField(blank=True, null=True),
        ),
    ]
