# Generated by Django 5.2.7 on 2025-10-23 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0009_alter_registrant_days_to_attend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='admn_number',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='National ID Number'),
        ),
        migrations.AlterField(
            model_name='registrant',
            name='days_to_attend',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
