# Generated by Django 5.2.7 on 2025-10-13 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0010_alter_registrant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='category',
            field=models.CharField(choices=[('', 'Select Category'), (2, 'Secretariat'), (3, 'Committee Member')], max_length=50, verbose_name='Registration Category'),
        ),
    ]
