# Generated by Django 5.2 on 2025-10-31 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("summitPage", "0011_alter_registrant_passport_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrant",
            name="is_printed",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
