# Generated by Django 5.2.7 on 2025-10-13 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0012_alter_registrant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='summitPage.category', verbose_name='Registration Category'),
        ),
    ]
