# Generated by Django 5.2.7 on 2025-10-13 13:23

import summitPage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0013_alter_registrant_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='category',
            field=models.CharField(choices=summitPage.models.get_category_choices, max_length=50, verbose_name='Registration Category'),
        ),
    ]
