# Generated by Django 5.2.7 on 2025-10-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0013_categorycolor_printlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
