# Generated by Django 5.2.7 on 2025-10-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0014_exhibitor_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
