# Generated by Django 5.2.7 on 2025-10-15 09:00

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0015_exhibitionsection_alter_registrant_category_booth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitor',
            name='beneficial_owner_details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='beneficial_owner_doc',
            field=models.FileField(blank=True, null=True, upload_to='uploads/exhibitors/owners_docs/'),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='business_registration_doc',
            field=models.FileField(blank=True, null=True, upload_to='uploads/exhibitors/business_docs/'),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='business_type',
            field=models.CharField(choices=[('local', 'Local (Kenyan)'), ('international', 'International')], default='local', help_text='Select whether this is a local or international business', max_length=20),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='country_of_registration',
            field=django_countries.fields.CountryField(default='UNKNOWN', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='international_business_doc',
            field=models.FileField(blank=True, null=True, upload_to='uploads/exhibitors/international_docs/'),
        ),
        migrations.AddField(
            model_name='exhibitor',
            name='kra_pin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='category',
            field=models.CharField(choices=[('', 'Select Category'), ('startup', 'Startup'), ('corporate', 'Corporate'), ('government', 'Government Agency'), ('academic', 'Academic Institution'), ('ngo', 'NGO'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='national_id_scan',
            field=models.FileField(upload_to='uploads/exhibitors/id_scans/'),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='passport_photo',
            field=models.ImageField(upload_to='uploads/exhibitors/photos/'),
        ),
        migrations.AlterField(
            model_name='exhibitor',
            name='title',
            field=models.CharField(choices=[('', 'Select Title'), ('Prof', 'Prof.'), ('Dr', 'Dr.'), ('Mr', 'Mr.'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.')], max_length=10),
        ),
        migrations.AlterField(
            model_name='summitpartner',
            name='logo',
            field=models.ImageField(help_text="Upload the partner's logo image", upload_to='uploads/partners/logos/'),
        ),
        migrations.AlterField(
            model_name='summitspeaker',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/speakers/'),
        ),
        migrations.CreateModel(
            name='BeneficialOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=100)),
                ('identification_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport')], max_length=20)),
                ('id_number', models.CharField(max_length=50)),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='uploads/exhibitors/ownership_docs/')),
                ('exhibitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owners', to='summitPage.exhibitor')),
            ],
        ),
    ]
