# Generated by Django 5.2.7 on 2025-10-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0016_exhibitor_beneficial_owner_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficialowner',
            name='nationality',
            field=models.CharField(max_length=500),
        ),
    ]
