# Generated by Django 5.2.7 on 2025-11-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summitPage', '0017_printlog_reprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrant',
            name='organization_type',
            field=models.CharField(choices=[('', 'Select Organization'), ('Government Agency', 'Government Agency'), ('Private Company', 'Private Company'), ('Academic Institution', 'Academic Institution'), ('Sector Association', 'Sector Association'), ('Industry Advocacy Groups', 'Industry Advocacy Groups'), ('Development Partners', 'Development Partners'), ('Student', 'Student'), ('Hackathon', 'Hackathon'), ('other', 'Others')], max_length=100),
        ),
    ]
